[package]
name = "bls_mps_wp"
version = "0.1.0"
authors = ["chuan"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bls12_381 = "0.4.0"
hex = "0.4.3"
rand = "0.8.3"
sha2 = "0.9.5"